twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_5_layout.html.twig
    paths:
        '%kernel.project_dir%/templates/front': 'template'

    globals:
        categoryRepository: "@App\\Repository\\CategoryRepository"
        productRepository: "@App\\Repository\\ProductRepository"

when@test:
    twig:
        strict_variables: true
